# Generated by Django 4.1.3 on 2022-12-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pitche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitcherName', models.TextField(blank=True, null=True)),
                ('pitchTitle', models.TextField(blank=True, null=True)),
                ('pitchIdea', models.TextField(blank=True, null=True)),
                ('askAmount', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pitche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pitche')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
